version: 0.{build}

branches:
  only:
    - master

install:
  - cmd: git clone https://github.com/ioquake/ioq3.git ../ioq3
  - cmd: premake5.exe gmake
  - cmd: set PATH=C:\msys64\usr\bin;%PATH%
  - cmd: bash -lc ""
  - cmd: bash -lc "pacman --noconfirm -S make"
  - cmd: bash -lc "pacman --noconfirm -S --force mingw-w64-i686-gcc"

build_script:
  - cmd: bash -lc "export PATH=/mingw32/bin:$PATH && cd $APPVEYOR_BUILD_FOLDER && cd build && make config=release_x86"

after_build:
  - cmd: 7z a renderer_bgfx_x86.zip %APPVEYOR_BUILD_FOLDER%\build\bin_x86\renderer_bgfx_x86.dll

artifacts:
  - path: renderer_bgfx_x86.zip
  
deploy:
- provider: BinTray
  username: jpcy
  api_key:
    secure: pLpGN6oHk8U7G5p4qUiMKoGgSTOB283MZSIFC30mPUQ4jMA1hGMeeD6tGSKsVJ3d
  subject: jpcy
  repo: ioq3-renderer-bgfx
  package: windows
  version: test
  publish: true
  override: true
